### ISSUE TITLE
Missing Server code

### ISSUE THREAD

**Issue by sanjeevghimire** [Build-Change/call_for_code#10]
`Readme.md` mentions about server code where the android app connects to but I don't see any server code in the repository.

**Comment by sanjeevghimire** [comment]
@kshitizrimal

**Comment by lizklipp** [comment]
@kshitizrimal hey there, just a friendly reminder we're looking for the server code if you can please update. thanks!

**Comment by stevemart** [comment]
Hi @kshitizrimal @Subhash2053 the last step of the README says:

> "Android Application" folder contains the android code which takes the picture and sends to the AI server and show the final output. To change the api for your own server go to MainApplication.java file and change "BASE_URL" value. ie : public static String BASE_URL = "Your API Code HERE";

Can you provide more detail here? There's no `MainApplication.java` file in the repo folders, as far as I can tell, there's no server specific code checked into the repo. So the Android app doesn't have anywhere to send the results to.

```
AI	--> related to creating model
Android	--> the android app code
Image generation --> related to creating model
```

**Comment by buildchange** [comment]
Hi @stevemar  It is MainActivity.java not MainApplication.java. Sorry for the inconvenience

**Comment by krook** [comment]
@buildchange I think the core question is where does the Android app send the image data so that it can be processed by the image recognition service, rather than anything specific to the mobile client.

**Comment by buildchange** [comment]
@krook As we create all the 3D model of houses to train the model before launching the application, So, for this stage we will have pre-train model and the API just compare and show the result whether the go houses or nogo houses for further inspection. But we are developing now in such way that image can store and retrain the model with additional image we get with mix of old 3D model we have for better accuracy.
