### ISSUE TITLE
Error while running `train.py`

### ISSUE THREAD

**Issue by sanjeevghimire** [Build-Change/call_for_code#5]
I am running this code base on mac with python 3.6. I get following error when i run
`python train.py`

```
Using TensorFlow backend.
2019-02-19 13:28:33.986447: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Device mapping: no known devices.
2019-02-19 13:28:33.988273: I tensorflow/core/common_runtime/direct_session.cc:297] Device mapping:

WARNING:tensorflow:From /usr/local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    model.fit(train_dataset, epochs=100, steps_per_epoch=10, validation_data=val_dataset, validation_steps=10, callbacks=[tensorboard])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/sequential.py", line 582, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1150, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 784, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training_utils.py", line 134, in standardize_input_data
    np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training_utils.py", line 134, in <listcomp>
    np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data
AttributeError: 'RepeatDataset' object has no attribute 'ndim'
```

**Comment by krook** [comment]
@buildchange @kshitizrimal any ideas on how to work through this one?

**Comment by kshitizrimal** [comment]
@sanjeevghimire It can be because, you are not specifying the path to the training dataset correctly. Download the numpy files from the google drive and put them inside "numpy_edge", make sure this folder is at the same location of "train.py" file and things should work.

**Comment by sanjeevghimire** [comment]
@kshitizrimal Can this be updated in the readme please if it’s a step part
of the application? I will try it. Thanks

**Comment by kshitizrimal** [comment]
@sanjeevghimire I think there is a link to readme file as well for the dataset. When you clone the repo, you can find an empty numpy_edge folder, just download the files from the google drive and put it there. We are sorry if the step is not that obvious. Good Luck

**Comment by sanjeevghimire** [comment]
The link is not there and there is empty numpy_edge folder. I do see a
readme inside that folder which mentions open cvs canny edge folder. The
readme wasn’t that clear. I will download and will work on making the
project run and make it clearer so that we can publish it sooner.

**Comment by sanjeevghimire** [comment]
Can you please send the download link if its handy?

**Comment by kshitizrimal** [comment]
its already in the readme file of AI directory, the same location where this train.py file is

https://github.com/Build-Change/call_for_code/tree/master/AI

**Comment by sanjeevghimire** [comment]
ok great thanks. The readme surely needs to be consolidated into one.
Thanks.

**Comment by sanjeevghimire** [comment]
Kshitiz,

I actually already have the dataset in that folder. When I run `python
train.py` I get this error:

Using TensorFlow backend.
2019-02-22 11:17:51.625764: I
tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports
instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Device mapping: no known devices.
2019-02-22 11:17:51.626595: I
tensorflow/core/common_runtime/direct_session.cc:297] Device mapping:

WARNING:tensorflow:From
/usr/local/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198:
retry (from tensorflow.contrib.learn.python.learn.datasets.base) is
deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Traceback (most recent call last):
  File "train.py", line 101, in <module>
    model.fit(train_dataset, epochs=100, steps_per_epoch=10,
validation_data=val_dataset, validation_steps=10, callbacks=[tensorboard])
  File
"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/sequential.py",
line 582, in fit
    validation_steps=validation_steps)
  File
"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py",
line 1150, in fit
    batch_size=batch_size)
  File
"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training.py",
line 784, in _standardize_user_data
    exception_prefix='input')
  File
"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training_utils.py",
line 134, in standardize_input_data
    np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in
data
  File
"/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/training_utils.py",
line 134, in <listcomp>
    np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in
data
AttributeError: 'RepeatDataset' object has no attribute 'ndim'

**Comment by kshitizrimal** [comment]
There is a chance that , it's something to do with the installation of tensorflow in your running device, because I just downloaded the code from the repo and re-ran it with the files provided in google drive, it worked fine. Can you check that in any other machine or with different installation?

**Comment by sanjeevghimire** [comment]
What version of tensorflow you using? I am using the same one listed in `requirements.txt`.

**Comment by sanjeevghimire** [comment]
@kshitizrimal I would love to do a webex/zoom if you have 15-30 mins to understand the issue.

**Comment by kshitizrimal** [comment]
@sanjeevghimire you can try and upgrade to latest ''1.12.0'' and I am using python 3.6.1 in my local machine where I tested. It runs perfectly fine with this configuration. I am not sure with this error here, probably not related to the code itself but rather the configuration of the machine. In such case you can search other answers on the internet with similar error.

**Comment by sanjeevghimire** [comment]
@kshitizrimal I did an upgrade. It did move forward but now ran into another issue: 
```Traceback (most recent call last):
  File "train.py", line 101, in <module>
    model.fit(train_dataset, epochs=100, steps_per_epoch=10, validation_data=val_dataset, validation_steps=10, callbacks=[tensorboard])
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 154, in fit_loop
    outs = f(ins)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable training/Adam/Variable_43 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/training/Adam/Variable_43/N10tensorflow3VarE does not exist.
	 [[{{node training/Adam/mul_68/ReadVariableOp}} = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](training/Adam/Variable_43)]]
 1  minikube  sanjeevghimire  ~/D/p/i/call_for_code   master  +2/-2 1...  AI```

**Comment by kshitizrimal** [comment]
@sanjeevghimire this is very unusual, but i still don't think its the problem with the source code files, but rather with the installation, may be this is due to separate Keras and Tensorflow installation in your system, but not sure. From 1.12 onwards, you can use tf.keras for all the keras related calls in the source code, as this code was before that, I used only Keras for the import and calls.

**Comment by krook** [comment]
@kshitizrimal Do you think that this merging this pull request would solve that problem? https://github.com/Build-Change/call_for_code/pull/8
