### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by sanjeevghimire** [Build-Change/call_for_code#9]
the script `evaluate_confusion_matrix.py` is referencing below files which are missing: 

```
x_test = np.load("numpy_edge/224_realall_features.npy")
y_test = np.load("numpy_edge/224_realall_labels.npy")
```

**Comment by sanjeevghimire** [comment]
@kshitizrimal ^

**Comment by kshitizrimal** [comment]
@sanjeevghimire Hi Sanjeeev, it looks like I used different test files to test the model, and you are right these files are not included in the drive. What you can do is, you can use the convert_data.py script to convert the files located in "Test Images for AI IBM" folder to convert to .npy files and use that for testing the model. These files are included but not in .npy file but rather in .jpg format, you can use "convert_data.py" file to convert any images into .npy file and use it for testing. Make sure you use correct directory name and location in the script.

**Comment by sanjeevghimire** [comment]
@kshitizrimal  I used the existing .npy files which were created from previous step and it seemed to work. The readme mentions about the `server`, is the server piece also missing here?

**Comment by sanjeevghimire** [comment]
closing this. I will create new one for the server part.
